import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {defineConfig, loadEnv} from 'vite';
import { resolve } from 'path';

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, '.', '');
  return {
    plugins: [react(), tailwindcss()],
    define: {
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    build: {
      rollupOptions: {
        input: {
          main: resolve(__dirname, 'index.html'),
          es_index: resolve(__dirname, 'es/index.html'),
          en_index: resolve(__dirname, 'en/index.html'),
          es_destinos: resolve(__dirname, 'es/destinos.html'),
          en_destinations: resolve(__dirname, 'en/destinations.html'),
          es_boquete: resolve(__dirname, 'es/boquete.html'),
          en_boquete: resolve(__dirname, 'en/boquete.html'),
          es_volcan_baru: resolve(__dirname, 'es/volcan-baru.html'),
          en_volcan_baru: resolve(__dirname, 'en/volcan-baru.html'),
          es_cerro_punta: resolve(__dirname, 'es/cerro-punta.html'),
          en_cerro_punta: resolve(__dirname, 'en/cerro-punta.html'),
          es_volcan: resolve(__dirname, 'es/volcan.html'),
          en_volcan: resolve(__dirname, 'en/volcan.html'),
          es_el_valle: resolve(__dirname, 'es/el-valle.html'),
          en_el_valle: resolve(__dirname, 'en/el-valle.html'),
          es_santa_fe: resolve(__dirname, 'es/santa-fe.html'),
          en_santa_fe: resolve(__dirname, 'en/santa-fe.html'),
          es_altos_campana: resolve(__dirname, 'es/altos-campana.html'),
          en_altos_campana: resolve(__dirname, 'en/altos-campana.html'),
          es_altos_maria: resolve(__dirname, 'es/altos-maria.html'),
          en_altos_maria: resolve(__dirname, 'en/altos-maria.html'),
          es_cerro_azul: resolve(__dirname, 'es/cerro-azul.html'),
          en_cerro_azul: resolve(__dirname, 'en/cerro-azul.html'),
          es_guadalupe: resolve(__dirname, 'es/guadalupe.html'),
          en_guadalupe: resolve(__dirname, 'en/guadalupe.html'),
          es_bambito: resolve(__dirname, 'es/bambito.html'),
          en_bambito: resolve(__dirname, 'en/bambito.html'),
          es_paso_ancho: resolve(__dirname, 'es/paso-ancho.html'),
          en_paso_ancho: resolve(__dirname, 'en/paso-ancho.html'),
          es_cuesta_piedra: resolve(__dirname, 'es/cuesta-piedra.html'),
          en_cuesta_piedra: resolve(__dirname, 'en/cuesta-piedra.html'),
          es_potrerillos: resolve(__dirname, 'es/potrerillos.html'),
          en_potrerillos: resolve(__dirname, 'en/potrerillos.html'),
          es_palmira: resolve(__dirname, 'es/palmira.html'),
          en_palmira: resolve(__dirname, 'en/palmira.html'),
          es_caldera: resolve(__dirname, 'es/caldera.html'),
          en_caldera: resolve(__dirname, 'en/caldera.html'),
          es_jaramillo: resolve(__dirname, 'es/jaramillo.html'),
          en_jaramillo: resolve(__dirname, 'en/jaramillo.html'),
          es_bajo_boquete: resolve(__dirname, 'es/bajo-boquete.html'),
          en_bajo_boquete: resolve(__dirname, 'en/bajo-boquete.html'),
          es_alto_boquete: resolve(__dirname, 'es/alto-boquete.html'),
          en_alto_boquete: resolve(__dirname, 'en/alto-boquete.html'),
          es_reserva_fortuna: resolve(__dirname, 'es/reserva-fortuna.html'),
          en_reserva_fortuna: resolve(__dirname, 'en/reserva-fortuna.html'),
          es_la_pintada: resolve(__dirname, 'es/la-pintada.html'),
          en_la_pintada: resolve(__dirname, 'en/la-pintada.html'),
          es_ola: resolve(__dirname, 'es/ola.html'),
          en_ola: resolve(__dirname, 'en/ola.html'),
          es_el_cope: resolve(__dirname, 'es/el-cope.html'),
          en_el_cope: resolve(__dirname, 'en/el-cope.html'),
          es_calobre: resolve(__dirname, 'es/calobre.html'),
          en_calobre: resolve(__dirname, 'en/calobre.html'),
          es_san_francisco: resolve(__dirname, 'es/san-francisco.html'),
          en_san_francisco: resolve(__dirname, 'en/san-francisco.html'),
          es_chica: resolve(__dirname, 'es/chica.html'),
          en_chica: resolve(__dirname, 'en/chica.html'),
          es_sora: resolve(__dirname, 'es/sora.html'),
          en_sora: resolve(__dirname, 'en/sora.html'),
          es_chitra: resolve(__dirname, 'es/chitra.html'),
          en_chitra: resolve(__dirname, 'en/chitra.html'),
          es_cerro_jefe: resolve(__dirname, 'es/cerro-jefe.html'),
          en_cerro_jefe: resolve(__dirname, 'en/cerro-jefe.html'),
          es_cerro_hoya: resolve(__dirname, 'es/cerro-hoya.html'),
          en_cerro_hoya: resolve(__dirname, 'en/cerro-hoya.html'),
          es_el_montuoso: resolve(__dirname, 'es/el-montuoso.html'),
          en_el_montuoso: resolve(__dirname, 'en/el-montuoso.html'),
          es_pn_volcan_baru: resolve(__dirname, 'es/parque-nacional-volcan-baru.html'),
          en_pn_volcan_baru: resolve(__dirname, 'en/parque-nacional-volcan-baru.html'),
          es_sendero_quetzales: resolve(__dirname, 'es/sendero-los-quetzales.html'),
          en_sendero_quetzales: resolve(__dirname, 'en/sendero-los-quetzales.html'),
          es_actividades: resolve(__dirname, 'es/actividades.html'),
          en_activities: resolve(__dirname, 'en/activities.html'),
          es_consejos: resolve(__dirname, 'es/consejos.html'),
          en_tips: resolve(__dirname, 'en/tips.html'),
          es_contacto: resolve(__dirname, 'es/contacto.html'),
          en_contact: resolve(__dirname, 'en/contact.html'),
          // Spanish Activities
          es_act_agroturismo: resolve(__dirname, 'es/actividades/agroturismo.html'),
          es_act_aventura: resolve(__dirname, 'es/actividades/aventura-naturaleza.html'),
          es_act_aves: resolve(__dirname, 'es/actividades/avistamiento-aves.html'),
          es_act_bienestar: resolve(__dirname, 'es/actividades/bienestar-relajacion.html'),
          es_act_camping: resolve(__dirname, 'es/actividades/camping-aire-libre.html'),
          es_act_compras: resolve(__dirname, 'es/actividades/compras-artesanias.html'),
          es_act_cultura: resolve(__dirname, 'es/actividades/cultura-gastronomia.html'),
          es_act_deportes: resolve(__dirname, 'es/actividades/deportes-aventura.html'),
          es_act_ecoturismo: resolve(__dirname, 'es/actividades/ecoturismo.html'),
          es_act_escenicas: resolve(__dirname, 'es/actividades/experiencias-escenicas.html'),
          es_act_rios: resolve(__dirname, 'es/actividades/rios-cascadas.html'),
          es_act_exploratorio: resolve(__dirname, 'es/actividades/turismo-exploratorio.html'),
          // English Activities
          en_act_adventure: resolve(__dirname, 'en/activities/adventure-nature.html'),
          en_act_agrotourism: resolve(__dirname, 'en/activities/agrotourism.html'),
          en_act_birdwatching: resolve(__dirname, 'en/activities/birdwatching.html'),
          en_act_camping: resolve(__dirname, 'en/activities/camping-outdoors.html'),
          en_act_culture: resolve(__dirname, 'en/activities/culture-gastronomy.html'),
          en_act_ecotourism: resolve(__dirname, 'en/activities/ecotourism.html'),
          en_act_exploratory: resolve(__dirname, 'en/activities/exploratory-tourism.html'),
          en_act_rivers: resolve(__dirname, 'en/activities/rivers-waterfalls.html'),
          en_act_scenic: resolve(__dirname, 'en/activities/scenic-experiences.html'),
          en_act_shopping: resolve(__dirname, 'en/activities/shopping-crafts.html'),
          en_act_sports: resolve(__dirname, 'en/activities/sports-adventure.html'),
          en_act_wellness: resolve(__dirname, 'en/activities/wellness-relaxation.html'),
        },
      },
    },
    server: {
      port: 3000,
      host: '0.0.0.0',
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
